spring:
  profiles:
    active: prod  # 기본 활성 프로파일을 prod로 설정
    include: hidden, hidden-dev
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: /temp
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    time-zone: Asia/Seoul


weatherperson:
  api:
    key: af176147adb1d200c47ff09f2f0bdc49
    url: https://api.openweathermap.org/data/2.5/forecast

server:
  port: 9090