spring:
  h2:
    console:
      enabled: true
      path: /h2     # H2 콘솔의 접속 URL을 간결하게 함
      datasource:
        url: jdbc:h2:mem:test  # JDBC URL이 매번 랜덤하게 바뀌지 않도록 고정
        username: sa
        password:
        driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#
#cloud:
#  aws:
#    credentials:
#      access-key: AKIAT5SBKEUB22ZY6USJ
#      secret-key: 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
#    region:
#      static: ap-northeast-2 # 사용 중인 AWS 리전
#    s3:
#      bucket: baseball-root-images
#    stack:
#      auto: false
