#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/baseball_root?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1234
spring:
  # 컨트롤러에서 프론트로 보내줄 때 null field 생략
  jackson:
    default-property-inclusion: non_null

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.165.85.56:3306/baseball_root
    username: test
    password: 123456

  sql:
    init:
      mode: never
      platform: mysql

  logging:
    level:
      org:
        hibernate:
          SQL: debug
        springframework:
          web: debug

